<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('question_bank', function (Blueprint $table) {
            $table->boolean('ai_generated')->default(false)->after('is_active')->comment('Was this question generated by AI?');
            $table->foreignId('ai_request_id')->nullable()->after('ai_generated')->constrained('ai_requests')->onDelete('set null')->comment('Reference to AI request that generated this');
            $table->json('ai_metadata')->nullable()->after('ai_request_id')->comment('AI generation metadata');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('question_bank', function (Blueprint $table) {
            $table->dropForeign(['ai_request_id']);
            $table->dropColumn(['ai_generated', 'ai_request_id', 'ai_metadata']);
        });
    }
};
