const fs = require('fs');
const path = require('path');
const ar = JSON.parse(fs.readFileSync(path.join(__dirname,'_doc_ar.json'), 'utf8'));
const pagesDir = path.join(__dirname,'..','resources','views','admin','docs','pages');

const slugScript = "document.addEventListener('DOMContentLoaded', function () {\n    var titleEl = document.getElementById('doc_title');\n    var slugEl  = document.getElementById('doc_slug');\n    var btn     = document.getElementById('doc_generate_slug');\n    function slugify(t) {\n        if (!t) return '';\n        return t.toString().trim()\n            .replace(/\\\\s+/g, '-')\n            .replace(/[^\\\\u0600-\\\\u06FFa-zA-Z0-9-]/g, '')\n            .replace(/-+/g, '-')\n            .replace(/^-+|-+\$/g, '') || ('page-' + Date.now());\n    }\n    if (titleEl && slugEl) {\n        titleEl.addEventListener('input', function () {\n            if (!slugEl.dataset.touched) slugEl.value = slugify(this.value);\n        });\n        slugEl.addEventListener('input', function () { this.dataset.touched = '1'; });\n    }\n    if (btn && titleEl && slugEl) {\n        btn.addEventListener('click', function () {\n            slugEl.value = slugify(titleEl.value);\n            delete slugEl.dataset.touched;\n        });\n    }\n});";

const L = "\n";

let c = "";
c += "@extends('admin.layouts.master')" + L + L;
c += "@section('page-title', '" + ar.addPageTitle + "')" + L + L;
c += "@section('styles')" + L;
c += "<link href=\"https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism.min.css\" rel=\"stylesheet\" />" + L;
c += "@endsection" + L + L;
c += "@section('content')" + L;
c += "<div class=\"main-content app-content\">" + L;
c += "    <div class=\"container-fluid\">" + L;
c += "        <div class=\"d-md-flex d-block align-items-center justify-content-between my-4 page-header-breadcrumb\">" + L;
c += "            <div>" + L;
c += "                <h4 class=\"mb-0\">" + ar.addPageTitle + "</h4>" + L;
c += "                <p class=\"mb-0 text-muted\">" + ar.addSubtitle + "</p>" + L;
c += "            </div>" + L;
c += "            <a href=\"{{ route('admin.docs.pages.index') }}\" class=\"btn btn-secondary\">" + ar.backList + "</a>" + L;
c += "        </div>" + L + L;
c += "        @if(\->any())" + L;
c += "        <div class=\"alert alert-danger alert-dismissible fade show\">" + L;
c += "            <ul class=\"mb-0\">@foreach(\->all() as \)<li>{{ \ }}</li>@endforeach</ul>" + L;
c += "            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>" + L;
c += "        </div>" + L;
c += "        @endif" + L + L;
c += "        <form action=\"{{ route('admin.docs.pages.store') }}\" method=\"POST\">" + L;
c += "            @csrf" + L;
c += "            <div class=\"row\">" + L;
c += "                <div class=\"col-lg-8\">" + L;
c += "                    <div class=\"card custom-card mb-4\">" + L;
c += "                        <div class=\"card-header\"><div class=\"card-title\">" + ar.contentBlock + "</div></div>" + L;
c += "                        <div class=\"card-body\">" + L;
c += "                            <div class=\"mb-3\">" + L;
c += "                                <label class=\"form-label\">" + ar.title + " <span class=\"text-danger\">*</span></label>" + L;
c += "                                <input type=\"text\" name=\"title\" id=\"doc_title\" class=\"form-control @error('title') is-invalid @enderror\" value=\"{{ old('title') }}\" required>" + L;
c += "                                @error('title')<div class=\"invalid-feedback\">{{ \ }}</div>@enderror" + L;
c += "                            </div>" + L;
c += "                            <div class=\"mb-3\">" + L;
c += "                                <label class=\"form-label\">" + ar.slugLabel + "</label>" + L;
c += "                                <div class=\"input-group\">" + L;
c += "                                    <input type=\"text\" name=\"slug\" id=\"doc_slug\" class=\"form-control @error('slug') is-invalid @enderror\" value=\"{{ old('slug') }}\" placeholder=\"" + ar.slugPh + "\">" + L;
c += "                                    <button type=\"button\" class=\"btn btn-outline-secondary\" id=\"doc_generate_slug\">" + ar.generate + "</button>" + L;
c += "                                </div>" + L;
c += "                                <small class=\"text-muted\">" + ar.slugHelp + "</small>" + L;
c += "                                @error('slug')<div class=\"invalid-feedback d-block\">{{ \ }}</div>@enderror" + L;
c += "                            </div>" + L;
c += "                            <div class=\"mb-3\">" + L;
c += "                                <label class=\"form-label\">" + ar.excerpt + "</label>" + L;
c += "                                <textarea name=\"excerpt\" rows=\"2\" class=\"form-control @error('excerpt') is-invalid @enderror\">{{ old('excerpt') }}</textarea>" + L;
c += "                                @error('excerpt')<div class=\"invalid-feedback\">{{ \ }}</div>@enderror" + L;
c += "                            </div>" + L;
c += "                            <div class=\"mb-0\">" + L;
c += "                                <label class=\"form-label\">" + ar.contentBlock + " <span class=\"text-danger\">*</span></label>" + L;
c += "                                <textarea name=\"content\" id=\"doc_content\" class=\"form-control @error('content') is-invalid @enderror\" rows=\"12\">{{ old('content') }}</textarea>" + L;
c += "                                @error('content')<div class=\"invalid-feedback\">{{ \ }}</div>@enderror" + L;
c += "                            </div>" + L;
c += "                        </div>" + L;
c += "                    </div>" + L + L;
c += "                    <div class=\"card custom-card mb-4\">" + L;
c += "                        <div class=\"card-header\"><div class=\"card-title\">SEO</div></div>" + L;
c += "                        <div class=\"card-body\">" + L;
c += "                            <div class=\"mb-3\">" + L;
c += "                                <label class=\"form-label\">" + ar.metaTitle + "</label>" + L;
c += "                                <input type=\"text\" name=\"meta_title\" class=\"form-control\" value=\"{{ old('meta_title') }}\" maxlength=\"255\">" + L;
c += "                            </div>" + L;
c += "                            <div class=\"mb-0\">" + L;
c += "                                <label class=\"form-label\">" + ar.metaDesc + "</label>" + L;
c += "                                <textarea name=\"meta_description\" rows=\"2\" class=\"form-control\">{{ old('meta_description') }}</textarea>" + L;
c += "                            </div>" + L;
c += "                        </div>" + L;
c += "                    </div>" + L;
c += "                </div>" + L + L;
c += "                <div class=\"col-lg-4\">" + L;
c += "                    <div class=\"card custom-card mb-4\">" + L;
c += "                        <div class=\"card-header\"><div class=\"card-title\">" + ar.taxStructure + "</div></div>" + L;
c += "                        <div class=\"card-body\">" + L;
c += "                            <div class=\"mb-3\">" + L;
c += "                                <label class=\"form-label\">" + ar.category + " <span class=\"text-danger\">*</span></label>" + L;
c += "                                <select name=\"documentation_category_id\" class=\"form-select @error('documentation_category_id') is-invalid @enderror\" required>" + L;
c += "                                    <option value=\"\">" + ar.choose + "</option>" + L;
c += "                                    @foreach(\ as \)" + L;
c += "                                    <option value=\"{{ \->id }}\" {{ (string) old('documentation_category_id', \) === (string) \->id ? 'selected' : '' }}>{{ \->name }}</option>" + L;
c += "                                    @endforeach" + L;
c += "                                </select>" + L;
c += "                                @error('documentation_category_id')<div class=\"invalid-feedback\">{{ \ }}</div>@enderror" + L;
c += "                            </div>" + L;
c += "                            <div class=\"mb-3\">" + L;
c += "                                <label class=\"form-label\">" + ar.parentPage + "</label>" + L;
c += "                                <select name=\"parent_id\" class=\"form-select\">" + L;
c += "                                    <option value=\"\">" + ar.none + "</option>" + L;
c += "                                    @foreach(\ as \ => \)" + L;
c += "                                    <option value=\"{{ \ }}\" {{ (string) old('parent_id') === (string) \ ? 'selected' : '' }}>{{ \ }}</option>" + L;
c += "                                    @endforeach" + L;
c += "                                </select>" + L;
c += "                                <small class=\"text-muted\">" + ar.parentHelp + "</small>" + L;
c += "                            </div>" + L;
c += "                            <div class=\"mb-3\">" + L;
c += "                                <label class=\"form-label\">" + ar.sortOrder + "</label>" + L;
c += "                                <input type=\"number\" name=\"sort_order\" class=\"form-control\" value=\"{{ old('sort_order', 0) }}\" min=\"0\">" + L;
c += "                            </div>" + L;
c += "                            <div class=\"mb-3\">" + L;
c += "                                <label class=\"form-label\">" + ar.status + " <span class=\"text-danger\">*</span></label>" + L;
c += "                                <select name=\"status\" class=\"form-select\" required>" + L;
c += "                                    <option value=\"draft\" {{ old('status', 'draft') === 'draft' ? 'selected' : '' }}>" + ar.draft + "</option>" + L;
c += "                                    <option value=\"published\" {{ old('status') === 'published' ? 'selected' : '' }}>" + ar.published + "</option>" + L;
c += "                                </select>" + L;
c += "                            </div>" + L;
c += "                            <div class=\"mb-3\">" + L;
c += "                                <label class=\"form-label\">" + ar.pubDate + "</label>" + L;
c += "                                <input type=\"datetime-local\" name=\"published_at\" class=\"form-control\" value=\"{{ old('published_at') }}\">" + L;
c += "                                <small class=\"text-muted\">" + ar.pubHint + "</small>" + L;
c += "                            </div>" + L;
c += "                            <div class=\"form-check\">" + L;
c += "                                <input class=\"form-check-input\" type=\"checkbox\" name=\"is_indexable\" value=\"1\" id=\"is_indexable\" {{ old('is_indexable', true) ? 'checked' : '' }}>" + L;
c += "                                <label class=\"form-check-label\" for=\"is_indexable\">" + ar.indexable + "</label>" + L;
c += "                            </div>" + L;
c += "                        </div>" + L;
c += "                    </div>" + L + L;
c += "                    <div class=\"card custom-card\">" + L;
c += "                        <div class=\"card-body\">" + L;
c += "                            <button type=\"submit\" class=\"btn btn-primary w-100 mb-2\"><i class=\"bi bi-save me-2\"></i>" + ar.save + "</button>" + L;
c += "                            <a href=\"{{ route('admin.docs.pages.index') }}\" class=\"btn btn-secondary w-100\">" + ar.cancel + "</a>" + L;
c += "                        </div>" + L;
c += "                    </div>" + L;
c += "                </div>" + L;
c += "            </div>" + L;
c += "        </form>" + L;
c += "    </div>" + L;
c += "</div>" + L;
c += "@endsection" + L + L;
c += "@section('scripts')" + L;
c += "@include('admin.docs.partials.tinymce-doc')" + L;
c += "<script>" + L;
c += slugScript + L;
c += "</script>" + L;
c += "@endsection" + L;

fs.mkdirSync(pagesDir, { recursive: true });
fs.writeFileSync(path.join(pagesDir,'create.blade.php'), c, 'utf8');
console.log('OK');
console.log(c.slice(0,120));
