const fs = require('fs');
const path = require('path');
const ar = JSON.parse(fs.readFileSync(path.join(__dirname,'_doc_ar.json'), 'utf8'));
const pagesDir = path.join(__dirname,'..','resources','views','admin','docs','pages');
const L = "\n";

const slugScript = "document.addEventListener('DOMContentLoaded', function () {\n    var titleEl = document.getElementById('doc_title');\n    var slugEl  = document.getElementById('doc_slug');\n    var btn     = document.getElementById('doc_generate_slug');\n    function slugify(t) {\n        if (!t) return '';\n        return t.toString().trim()\n            .replace(/\\\\s+/g, '-')\n            .replace(/[^\\\\u0600-\\\\u06FFa-zA-Z0-9-]/g, '')\n            .replace(/-+/g, '-')\n            .replace(/^-+|-+\$/g, '') || ('page-' + Date.now());\n    }\n    if (btn && titleEl && slugEl) {\n        btn.addEventListener('click', function () {\n            slugEl.value = slugify(titleEl.value);\n        });\n    }\n});";

let e = "";
e += "@extends('admin.layouts.master')" + L + L;
e += "@section('page-title', '" + ar.editPageTitle + "')" + L + L;
e += "@section('styles')" + L;
e += "<link href=\"https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism.min.css\" rel=\"stylesheet\" />" + L;
e += "@endsection" + L + L;
e += "@section('content')" + L;
e += "<div class=\"main-content app-content\">" + L;
e += "    <div class=\"container-fluid\">" + L;
e += "        <div class=\"d-md-flex d-block align-items-center justify-content-between my-4 page-header-breadcrumb\">" + L;
e += "            <div>" + L;
e += "                <h4 class=\"mb-0\">" + ar.editPageTitle + ": {{ \->title }}</h4>" + L;
e += "                <p class=\"mb-0 text-muted\"><code>{{ \->slug }}</code></p>" + L;
e += "            </div>" + L;
e += "            <a href=\"{{ route('admin.docs.pages.index') }}\" class=\"btn btn-secondary\">" + ar.backList + "</a>" + L;
e += "        </div>" + L + L;
e += "        @if(\->any())" + L;
e += "        <div class=\"alert alert-danger alert-dismissible fade show\">" + L;
e += "            <ul class=\"mb-0\">@foreach(\->all() as \)<li>{{ \ }}</li>@endforeach</ul>" + L;
e += "            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>" + L;
e += "        </div>" + L;
e += "        @endif" + L + L;
e += "        @if(session('success'))" + L;
e += "        <div class=\"alert alert-success alert-dismissible fade show\">{{ session('success') }}" + L;
e += "            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>" + L;
e += "        </div>" + L;
e += "        @endif" + L + L;
e += "        <form action=\"{{ route('admin.docs.pages.update', \) }}\" method=\"POST\">" + L;
e += "            @csrf" + L;
e += "            @method('PUT')" + L;
e += "            <div class=\"row\">" + L;
e += "                <div class=\"col-lg-8\">" + L;
e += "                    <div class=\"card custom-card mb-4\">" + L;
e += "                        <div class=\"card-header\"><div class=\"card-title\">" + ar.contentBlock + "</div></div>" + L;
e += "                        <div class=\"card-body\">" + L;
e += "                            <div class=\"mb-3\">" + L;
e += "                                <label class=\"form-label\">" + ar.title + " <span class=\"text-danger\">*</span></label>" + L;
e += "                                <input type=\"text\" name=\"title\" id=\"doc_title\" class=\"form-control @error('title') is-invalid @enderror\" value=\"{{ old('title', \->title) }}\" required>" + L;
e += "                                @error('title')<div class=\"invalid-feedback\">{{ \ }}</div>@enderror" + L;
e += "                            </div>" + L;
e += "                            <div class=\"mb-3\">" + L;
e += "                                <label class=\"form-label\">" + ar.slugLabel + "</label>" + L;
e += "                                <div class=\"input-group\">" + L;
e += "                                    <input type=\"text\" name=\"slug\" id=\"doc_slug\" class=\"form-control @error('slug') is-invalid @enderror\" value=\"{{ old('slug', \->slug) }}\">" + L;
e += "                                    <button type=\"button\" class=\"btn btn-outline-secondary\" id=\"doc_generate_slug\">" + ar.generate + "</button>" + L;
e += "                                </div>" + L;
e += "                                @error('slug')<div class=\"invalid-feedback d-block\">{{ \ }}</div>@enderror" + L;
e += "                            </div>" + L;
e += "                            <div class=\"mb-3\">" + L;
e += "                                <label class=\"form-label\">" + ar.excerpt + "</label>" + L;
e += "                                <textarea name=\"excerpt\" rows=\"2\" class=\"form-control @error('excerpt') is-invalid @enderror\">{{ old('excerpt', \->excerpt) }}</textarea>" + L;
e += "                                @error('excerpt')<div class=\"invalid-feedback\">{{ \ }}</div>@enderror" + L;
e += "                            </div>" + L;
e += "                            <div class=\"mb-0\">" + L;
e += "                                <label class=\"form-label\">" + ar.contentBlock + " <span class=\"text-danger\">*</span></label>" + L;
e += "                                <textarea name=\"content\" id=\"doc_content\" class=\"form-control @error('content') is-invalid @enderror\" rows=\"12\">{{ old('content', \->content) }}</textarea>" + L;
e += "                                @error('content')<div class=\"invalid-feedback\">{{ \ }}</div>@enderror" + L;
e += "                            </div>" + L;
e += "                        </div>" + L;
e += "                    </div>" + L + L;
e += "                    <div class=\"card custom-card mb-4\">" + L;
e += "                        <div class=\"card-header\"><div class=\"card-title\">SEO</div></div>" + L;
e += "                        <div class=\"card-body\">" + L;
e += "                            <div class=\"mb-3\">" + L;
e += "                                <label class=\"form-label\">" + ar.metaTitle + "</label>" + L;
e += "                                <input type=\"text\" name=\"meta_title\" class=\"form-control\" value=\"{{ old('meta_title', \->meta_title) }}\" maxlength=\"255\">" + L;
e += "                            </div>" + L;
e += "                            <div class=\"mb-0\">" + L;
e += "                                <label class=\"form-label\">" + ar.metaDesc + "</label>" + L;
e += "                                <textarea name=\"meta_description\" rows=\"2\" class=\"form-control\">{{ old('meta_description', \->meta_description) }}</textarea>" + L;
e += "                            </div>" + L;
e += "                        </div>" + L;
e += "                    </div>" + L;
e += "                </div>" + L + L;
e += "                <div class=\"col-lg-4\">" + L;
e += "                    <div class=\"card custom-card mb-4\">" + L;
e += "                        <div class=\"card-header\"><div class=\"card-title\">" + ar.taxStructure + "</div></div>" + L;
e += "                        <div class=\"card-body\">" + L;
e += "                            <div class=\"mb-3\">" + L;
e += "                                <label class=\"form-label\">" + ar.category + " <span class=\"text-danger\">*</span></label>" + L;
e += "                                <select name=\"documentation_category_id\" class=\"form-select @error('documentation_category_id') is-invalid @enderror\" required>" + L;
e += "                                    @foreach(\ as \)" + L;
e += "                                    <option value=\"{{ \->id }}\" {{ (string) old('documentation_category_id', \->documentation_category_id) === (string) \->id ? 'selected' : '' }}>{{ \->name }}</option>" + L;
e += "                                    @endforeach" + L;
e += "                                </select>" + L;
e += "                                @error('documentation_category_id')<div class=\"invalid-feedback\">{{ \ }}</div>@enderror" + L;
e += "                            </div>" + L;
e += "                            <div class=\"mb-3\">" + L;
e += "                                <label class=\"form-label\">" + ar.parentPage + "</label>" + L;
e += "                                <select name=\"parent_id\" class=\"form-select\">" + L;
e += "                                    <option value=\"\">" + ar.none + "</option>" + L;
e += "                                    @foreach(\ as \ => \)" + L;
e += "                                    <option value=\"{{ \ }}\" {{ (string) old('parent_id', \->parent_id) === (string) \ ? 'selected' : '' }}>{{ \ }}</option>" + L;
e += "                                    @endforeach" + L;
e += "                                </select>" + L;
e += "                            </div>" + L;
e += "                            <div class=\"mb-3\">" + L;
e += "                                <label class=\"form-label\">" + ar.sortOrder + "</label>" + L;
e += "                                <input type=\"number\" name=\"sort_order\" class=\"form-control\" value=\"{{ old('sort_order', \->sort_order) }}\" min=\"0\">" + L;
e += "                            </div>" + L;
e += "                            <div class=\"mb-3\">" + L;
e += "                                <label class=\"form-label\">" + ar.status + " <span class=\"text-danger\">*</span></label>" + L;
e += "                                <select name=\"status\" class=\"form-select\" required>" + L;
e += "                                    <option value=\"draft\" {{ old('status', \->status) === 'draft' ? 'selected' : '' }}>" + ar.draft + "</option>" + L;
e += "                                    <option value=\"published\" {{ old('status', \->status) === 'published' ? 'selected' : '' }}>" + ar.published + "</option>" + L;
e += "                                </select>" + L;
e += "                            </div>" + L;
e += "                            <div class=\"mb-3\">" + L;
e += "                                <label class=\"form-label\">" + ar.pubDate + "</label>" + L;
e += "                                <input type=\"datetime-local\" name=\"published_at\" class=\"form-control\" value=\"{{ old('published_at', \->published_at?->format('Y-m-d\\\\TH:i')) }}\">" + L;
e += "                            </div>" + L;
e += "                            <div class=\"form-check\">" + L;
e += "                                <input class=\"form-check-input\" type=\"checkbox\" name=\"is_indexable\" value=\"1\" id=\"is_indexable\" {{ old('is_indexable', \->is_indexable) ? 'checked' : '' }}>" + L;
e += "                                <label class=\"form-check-label\" for=\"is_indexable\">" + ar.indexable + "</label>" + L;
e += "                            </div>" + L;
e += "                        </div>" + L;
e += "                    </div>" + L + L;
e += "                    <div class=\"card custom-card mb-4\">" + L;
e += "                        <div class=\"card-body\">" + L;
e += "                            <button type=\"submit\" class=\"btn btn-primary w-100 mb-2\"><i class=\"bi bi-save me-2\"></i>" + ar.saveChanges + "</button>" + L;
e += "                            <a href=\"{{ route('admin.docs.pages.index') }}\" class=\"btn btn-secondary w-100\">" + ar.back + "</a>" + L;
e += "                        </div>" + L;
e += "                    </div>" + L;
e += "                </div>" + L;
e += "            </div>" + L;
e += "        </form>" + L + L;
e += "        <div class=\"row\">" + L;
e += "            <div class=\"col-lg-4 ms-lg-auto\">" + L;
e += "                <div class=\"card custom-card\">" + L;
e += "                    <div class=\"card-header\"><div class=\"card-title\">" + ar.quickActions + "</div></div>" + L;
e += "                    <div class=\"card-body\">" + L;
e += "                        <form action=\"{{ route('admin.docs.pages.toggle-publish', \) }}\" method=\"POST\" class=\"mb-2\">" + L;
e += "                            @csrf" + L;
e += "                            <button type=\"submit\" class=\"btn btn-outline-secondary w-100\">" + ar.togglePub + "</button>" + L;
e += "                        </form>" + L;
e += "                        <form action=\"{{ route('admin.docs.pages.destroy', \) }}\" method=\"POST\" onsubmit=\"return confirm('" + ar.delConfirm + "');\">" + L;
e += "                            @csrf" + L;
e += "                            @method('DELETE')" + L;
e += "                            <button type=\"submit\" class=\"btn btn-outline-danger w-100\">" + ar.delPage + "</button>" + L;
e += "                        </form>" + L;
e += "                    </div>" + L;
e += "                </div>" + L;
e += "            </div>" + L;
e += "        </div>" + L;
e += "    </div>" + L;
e += "</div>" + L;
e += "@endsection" + L + L;
e += "@section('scripts')" + L;
e += "@include('admin.docs.partials.tinymce-doc')" + L;
e += "<script>" + L;
e += slugScript + L;
e += "</script>" + L;
e += "@endsection" + L;

fs.writeFileSync(path.join(pagesDir,'edit.blade.php'), e, 'utf8');
console.log('edit OK');
console.log(e.slice(0,120));
